### ISSUE TITLE
Choosing an Item or Animal for Icon Theme

### ISSUE THREAD

**Issue by BalmaBrian** [Team-Monogram/Reading-Rainbow#1]
We need to chose an item or creature to represent our app.

**Comment by BalmaBrian** [comment]
@Team-Monogram/sbhacks-the-brians Do you prefer a creature or an item?

**Comment by brianly01** [comment]
I think we could do a book being shown through a translucent phone, like the book's contents are transitioned into an image on the phone.

**Comment by brianly01** [comment]
Modelling after our PWA, we have a page from a book being projected onto the phone's screen. In the foreground is a phone with a full color image of a page in the book, with the screen lit up. The contents of the books is positioned behind it like a shadow darker in color. The is in the background out of focus, somewhat translucent showing up behind the phone.

**Comment by brianly01** [comment]
![Untitled-Artwork](https://user-images.githubusercontent.com/60518547/104806631-d2964200-578d-11eb-965c-8d479284da20.png)

**Comment by BalmaBrian** [comment]
I agree with the design. @brianly01 you can close this issue.
