### ISSUE TITLE
Illustrate final design of icon

### ISSUE THREAD

**Issue by BalmaBrian** [Team-Monogram/Reading-Rainbow#22]

**Comment by BalmaBrian** [comment]
Working on design on figma.

**Comment by BalmaBrian** [comment]
https://www.figma.com/file/rD1WRHgld3aXEm6HFB9RWI/Icon?node-id=0%3A1

**Comment by BalmaBrian** [comment]
I illustrated the design what do yall think? @Team-Monogram/sbhacks-the-brians 
![Icon](https://user-images.githubusercontent.com/44687168/104820252-73b1e680-57e8-11eb-954c-8bde85226a05.png)

**Comment by BalmaBrian** [comment]
That is an png but it is only 128x128. I have an svg version that I think we can use to make the other icons no problem.

**Comment by brianly01** [comment]
Looks good, but I think the part of the book you view through the phone screen could be full focus, while the other parts are out of focus.

**Comment by BalmaBrian** [comment]
all the icons were created in issue #23
