### ISSUE TITLE
Color pallet

### ISSUE THREAD

**Issue by BalmaBrian** [Team-Monogram/Reading-Rainbow#6]
This color pallet will be used for our logo/icons as well as our website color pallet.

**Comment by brianly01** [comment]
We want something easy on the eyes and not too harsh to read at night, so maybe gray or beige. with the text being black. We don't want a lot of contrast.

**Comment by brianly01** [comment]
Found some RGB values for the [palette](https://www.color-hex.com/color-palette/5361)

**Comment by BalmaBrian** [comment]
Perfect, lets add the color pallet to our css file.

**Comment by brianly01** [comment]
I decided to switch our palette to something easier to read, that I found on this [document](https://www.cs.cmu.edu/~jbigham/pubs/pdfs/2017/colors.pdf).

**Comment by brianly01** [comment]
Added in main.css file in public directory created in issue #5
